My_Admin/urls.py
from django.urls import path
from My_Admin import views
app_name='App_Admin'
urlpatterns = [

    path('ajax/load-districts/', views.load_district, name='ajax_load_district'),
    path('ajax/load-sub-districts/', views.load_sub_district, name='ajax_load_sub_district'),
    path('', views.Dashboard, name='dashboard'),
    path('superadmin-login', views.SuperadminLogin, name="superadmin_login"),
    path('superadmin-logout', views.SuperadminLogout, name="superadmin_logout"),

    path('division-page',views.Divisionmanagement,name='division_page'),
    path('division-delete',views.DivisionDelete,name='division_delete'),
    path('division-update/<int:id>',views.DivisionUpdate,name='division_update'),

    path('district-page',views.Districtmanagement,name='district_page'),
    path('district-delete',views.DistrictDelete,name='district_delete'),
    path('district-update/<int:id>',views.DistrictUpdate,name='district_update'),

    path('sub_district-page', views.Sub_Districtmanagement, name='sub_district_page'),
    path('sub_district-delete', views.Sub_DistrictDelete, name='sub_district_delete'),
    path('sub_district-update/<int:id>', views.Sub_DistrictUpdate, name='sub_district_update'),

    path('tourist-place', views.TouristPlacesview, name='tourist_place'),
    path('add-place', views.Add_Touristplaceview, name='add_place'),
    path('delete-place', views.Delete_Touristplaceview, name='delete_place'),
    path('update-place/<int:id>', views.Touristplaceupdate, name='update_tourist'),

    path('top-rated-place', views.TopratedPlacesview, name='top_rated_place'),
    path('add-top-rated-place', views.Add_Topratedplace, name='add_top_rated_place'),
    path('delete-top-rated-place', views.Delete_Topratedplace, name='delete_top_rated_place'),
    path('update-top-rated-place/<int:id>', views.Topratedplaceupdate, name='update_toprated_place'),

    path('place-order', views.Placeorderview, name='place_order_view'),
    path('delete-place-order', views.Delete_placeorder, name='delete_place_order'),
    path('update-place-order/<int:id>', views.Update_placeorder, name='update_place_order'),

    path('toprated-place-order', views.Topratedplaceorderview, name='top_rated_place_order_view'),
    path('toprated-delete-place-order', views.Delete_topratedplaceorder, name='delete_toprated_place_order'),
    path('toprated-update-place-order/<int:id>', views.Update_topratedplaceorder, name='update_toprated_place_order'),


    path('hotel-manage', views.Hotelmanage, name='manage_hotel'),
    path('delete-hotel', views.Delete_Hotel, name='delete_hotel'),
    path('update-hotel/<int:id>', views.Update_Hotel, name='update_hotel'),

    path('food-manage', views.Foodmanage, name='manage_food'),
    path('delete-food', views.Delete_Food, name='delete_food'),
    path('update-food/<int:id>', views.Update_Food, name='update_food'),

    path('nearest-place-manage', views.Nearestplacemanage, name='manage_nearest_place'),
    path('delete-nearest-place', views.Delete_Nearest_place, name='delete_nearest_place'),
    path('update-nearest-place/<int:id>', views.Update_Nearest_place, name='update_nearest_place'),

    path('view-guider', views.Guiderview, name='view_guider'),
    path('add-guider', views.Add_Guider, name='add_guider'),
    path('delete-guider', views.Delete_Guider, name='delete_guider'),
    path('update-guider/<int:id>', views.Update_Guider, name='update_guider'),

    path('view-hireguider', views.Hireguiderview, name='view_hireguider'),
    path('delete-hireguider', views.Delete_Hireguider, name='delete_hireguider'),
    path('update-hireguider/<int:id>', views.Update_Hireguider, name='update_hireguider'),

    path('user-profile/<int:id>',views.Userprofile,name='user_profile'),

]

event/urls.py
from django.urls import path
from .views import TouristEventView,event_profile_view,event_requriement,payment,payment_status,edit_profile_view,\
    payment_complete,completepurchase,event_status

urlpatterns = [
path('create-event/',TouristEventView,name='create-event'),
path('profile/',event_profile_view,name='profile'),
path('event-status/<int:id>',event_status,name='event_status'),
path('edit-profile/',edit_profile_view,name='edit_profile'),
path('event-requriement/<int:id>',event_requriement,name='event-requriementfile'),
path('event-payment/<int:id>', payment,name='event_payment'),
path('payment-complete', payment_complete,name='payment_complete'),
path('complete-purchased/<val_id>/<tran_id>/', completepurchase, name="completepurchase"),
path('status/', payment_status,name='payment_status')
]

tourist_guide/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tourist.urls')),
    path('account/', include('account.urls')),
    path('event/', include('event.urls')),
    path('places',include('places.urls')),
    path('superadmin/',include('My_Admin.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

places/models.py
from django.urls import reverse
from django.utils.datetime_safe import datetime
from tourist.models import Subscriber
from account.models import User
from django.db import models
from django.db.models.signals import post_save
# Create your models here.
from django.core.mail import send_mail, EmailMessage
from django.dispatch import receiver


# Create your models here.

class Ratting(models.Model):
    place = models.ForeignKey(to="TouristPlaces", on_delete=models.CASCADE,related_name="place")
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    score = models.IntegerField(default=0)

    def __str__(self):
        return '{}-{}-{}'.format(self.place, self.user, self.score)


class Division(models.Model):
    name = models.CharField(blank=False, max_length=30)

    def __str__(self):
        return self.name


class District(models.Model):
    division = models.ForeignKey(Division, on_delete=models.CASCADE)
    name = models.CharField(blank=False, max_length=30)
    map_url=models.TextField(default="",blank=True)

    def __str__(self):
        return self.name
    def get_place_count(self):
        return TouristPlaces.objects.filter(district=self).count()

class Sub_District(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(blank=False, max_length=30)

    def __str__(self):
        return self.name


class TouristPlaces(models.Model):
    place_name = models.CharField(max_length=200, blank=False)
    description = models.TextField(blank=False)
    image = models.ImageField(upload_to="places/", blank=False)
    ratting = models.ForeignKey(Ratting,null=True, blank=True,on_delete=models.CASCADE,related_name="ratting")
    price=models.IntegerField(default=200)
    division=models.ForeignKey(Division,on_delete=models.SET_NULL, null=True)
    district=models.ForeignKey(District,on_delete=models.SET_NULL, null=True)
    sub_district=models.ForeignKey(Sub_District,on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return '{}-{}'.format(self.place_name,self.price)

    def count_total_ratting(self):
        return Ratting.objects.filter(place=self).count()

    def count_avg_ratting(self):
        n=Ratting.objects.filter(place=self)
        total_ratting=Ratting.objects.filter(place=self).count()
        avg=0.0
        if total_ratting>0:
            all_score=0
            for i in n:
                all_score=all_score+i.score
            print (all_score)
            avg=all_score/total_ratting
        return format(avg,".1f")

@receiver(post_save, sender=TouristPlaces)
def create_profile(sender, instance, created, **kwargs):
    if created:
        all_email=Subscriber.objects.all()
        all=[]
        for i in all_email:
            all.append(i.email)

        mail_subject ='New Place Added'
        message="Please check our new place that are now available in our website"
        email = EmailMessage(
            mail_subject, message, to=all
        )
        email.send()


class Hotels(models.Model):
    sub_district=models.ForeignKey(Sub_District,on_delete=models.SET_NULL, null=True)
    name=models.CharField(max_length=100,blank=False)

    def __str__(self):
        return '{}-{}'.format(self.name,self.sub_district)

class NearestPlace(models.Model):
    sub_district = models.ForeignKey(Sub_District, on_delete=models.SET_NULL, null=True)
    name=models.CharField(max_length=100,blank=False)

    def __str__(self):
        return '{}-{}'.format(self.name,self.sub_district)

class FamousFood(models.Model):
    sub_district = models.ForeignKey(Sub_District, on_delete=models.SET_NULL, null=True)
    name=models.CharField(max_length=100,blank=False)

    def __str__(self):
        return '{}-{}'.format(self.name,self.sub_district)

class Order(models.Model):
    place = models.ForeignKey(TouristPlaces, on_delete=models.DO_NOTHING)
    start_date = models.DateField(auto_now=False)
    end_date = models.DateField(auto_now=False)
    person = models.IntegerField(default=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now=True)
    transaction_id = models.CharField(max_length=500,default="")
    ammount = models.FloatField(max_length=100,default=0.0)
    card_type = models.CharField(max_length=100,default="")
    payment_status = models.CharField(max_length=100,default="")
    transaction_date = models.CharField(max_length=100,default="")
    risk_title = models.CharField(max_length=100,default="")

    def __str__(self):
        return '{}'.format(self.user)

    def get_absolute_url(self):
        return reverse('place_requriementfile', kwargs={'id': self.id})

class Placeorder(models.Model):
    place = models.ForeignKey(TouristPlaces, on_delete=models.DO_NOTHING)
    start_date = models.DateField(auto_now=False)
    end_date = models.DateField(auto_now=False)
    person = models.IntegerField(default=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now=True)
    transaction_id = models.CharField(max_length=500,default="")
    ammount = models.FloatField(max_length=100,default=0.0)
    card_type = models.CharField(max_length=100,default="",blank=True)
    payment_status = models.CharField(max_length=100,default="",blank=True)
    transaction_date = models.CharField(max_length=100,default="",blank=True)
    risk_title = models.CharField(max_length=100,default="",blank=True)


    def get_absolute_url(self):
        return reverse('place_requriementfile', kwargs={'id': self.id})


class Topratedplace(models.Model):
    title=models.CharField(max_length=120)
    slug=models.CharField(max_length=200)
    description=models.TextField(default="Description text will be added here")
    image=models.ImageField(upload_to="Top Rated/",blank=False)
    price = models.IntegerField(default=1500)
    division = models.ForeignKey(Division, on_delete=models.SET_NULL, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    sub_district = models.ForeignKey(Sub_District, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return '{}-{}'.format(self.title,self.slug)


@receiver(post_save, sender=Topratedplace)
def create_profile(sender, instance, created, **kwargs):
    if created:
        all_email=Subscriber.objects.all()
        all=[]
        for i in all_email:
            all.append(i.email)

        mail_subject ='Top Rated Place Added'
        message="Please check our new top rated place that are now available in our website"
        email = EmailMessage(
            mail_subject, message, to=all
        )
        email.send()

class TopPlaceorder(models.Model):
    place = models.ForeignKey(Topratedplace, on_delete=models.DO_NOTHING)
    start_date = models.DateField(auto_now=False)
    end_date = models.DateField(auto_now=False)
    person = models.IntegerField(default=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now=True)
    transaction_id = models.CharField(max_length=500,default="")
    ammount = models.FloatField(max_length=100,default=0.0)
    card_type = models.CharField(max_length=100, default="", blank=True)
    payment_status = models.CharField(max_length=100, default="", blank=True)
    transaction_date = models.CharField(max_length=100, default="", blank=True)
    risk_title = models.CharField(max_length=100, default="", blank=True)

    def get_absolute_url(self):
        return reverse('payment', kwargs={'id': self.id})

templates/App_Admin/add_touristplace.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-lg-8  m-0 m-auto">
    {%for message in messages %}
        {%if "add_place" in message.tags %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
</div>
<div class="container">
    <div class="row mb-3">
          <div class="col-lg-8 m-0 m-auto">
              <div class="card p-4 mb-4">
              <h2>Add Tourist Place</h2>
              <form method="post" id="TouristForm" action="" enctype="multipart/form-data" data-sub-district-url="{% url 'App_Admin:ajax_load_sub_district' %}" data-district-url="{% url 'App_Admin:ajax_load_district' %}" novalidate>{% csrf_token %}
                  {{ form|crispy }}
                  <input type="hidden" name="next" value="{{ request.path }}">
                  <button type="submit" class="btn btn-primary">Add</button>
              </form>
                </div>
          </div>
    </div>

</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_division").change(function () {
      var url = $("#TouristForm").attr("data-district-url");
      var districtId = $(this).val();
      console.log(url);
      $.ajax({
        url: url,
        data: {
          'division': districtId,
        },
        success: function (data) {
          $("#id_district").html(data);
        }
      });

    });

    $("#id_district").change(function () {
      var url = $("#TouristForm").attr("data-sub-district-url");
      var subdistrictId = $(this).val();
      console.log(url);
      $.ajax({
        url: url,
        data: {
          'district': subdistrictId,
        },
        success: function (data) {
          $("#id_sub_district").html(data);
        }
      });

    });
  </script>

{% endblock %}

templates/App_Admin/hireguiderview.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-lg-12  m-0 m-auto">
    {%for message in messages %}
        {%if "delete_hireguider" in message.tags %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
</div>
<div class="container">
          <div class="row mb-3">
          <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Hire Guider List</h6>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                    <thead class="thead-light">
                      <tr>
                        <th>No</th>
                        <th>Guider Name</th>
                        <th>Hired By</th>
                        <th>Total Hour</th>
                        <th>Hired By</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Action</th>
                      </tr>

                    </thead>
                    <tbody>
                    {% for g in all_hireguider %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ g.guider_name }}</td>
                      <td><a href="{% url 'App_Admin:user_profile' g.user.id %}">{{ g.user.name }}</a></td>
                        <td>{{ g.hour }}</td>
                        <td>{{ g.user }}</td>
                        <td>{{ g.ammount }}</td>
                        <td>
                            {% if g.ordered == True %}
                            <i class="fa fa-check-circle text-success"></i>
                            {% else %}
                            <i class="fa fa-clock text-danger"></i>
                            {% endif %}
                        </td>
                        <td>
                          <button style="border: none;background: no-repeat;outline: none;" data-toggle="modal" value="{{ g.id }}" data-target="#hireguider_delete">
                                <i class="fa fa-trash text-danger"></i></button>
                            <a href="{% url 'App_Admin:update_hireguider' g.id %}"><i class="text-primary fas fa-fw fa-edit" style="color: #801d3b;"></i></a>
                        </td>
                      </tr>
                     {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
    $("button").click(function() {
    var fired_button = $(this).val();
    document.getElementById("hireguider_id").value = fired_button;

});
</script>
<div class="modal fade" id="hireguider_delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form  action="{% url 'App_Admin:delete_hireguider' %}" method="post">{% csrf_token %}
                    <h3 class="text-center text-danger">Delete Hire </h3><br>
                    <p class="text-center text-success">Are you sure you want to delete this hire?</p>
                    <input name="hireguider_id" id="hireguider_id" value="" type="hidden">
                    <div class="clearfix text-center">
                        <button type="button" data-dismiss="modal" class="cancelbtn btn btn-success">Cancel</button>
                        <button type="submit" class="deletebtn btn btn-danger">Delete</button>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

templates/App_Admin/manage_placeorder.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-lg-12  m-0 m-auto">
    {%for message in messages %}
        {%if "delete_order" in message.tags %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
</div>
<div class="container">
          <div class="row mb-3">
          <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Tourist Places Order List</h6>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                    <thead class="thead-light">
                      <tr>
                        <th>No</th>
                        <th>Place Name</th>
                        <th>Order By</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Person</th>
                        <th>Satus</th>
                        <th>Action</th>
                      </tr>

                    </thead>
                    <tbody>
                    {% for g in all_place %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ g.place.place_name }}</td>
                        <td><a href="{% url 'App_Admin:user_profile' g.user.id %}">{{ g.user.name }}</a></td>
                        <td>{{ g.start_date }}</td>
                        <td>{{ g.end_date }}</td>
                        <td>{{ g.person }}</td>
                        <td>
                            {% if g.ordered == True %}
                            <i class="fa fa-check-circle text-success"></i>
                            {% else %}
                            <i class="fa fa-clock text-danger"></i>
                            {% endif %}
                        </td>
                        <td>
                          <button style="border: none;background: no-repeat;outline: none;" data-toggle="modal" value="{{ g.id }}" data-target="#place_order">
                                <i class="fa fa-trash text-danger"></i></button>
                            <a href="{% url 'App_Admin:update_place_order' g.id %}"><i class="text-primary fas fa-fw fa-edit" style="color: #801d3b;"></i></a>
                        </td>
                      </tr>
                     {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
    $("button").click(function() {
    var fired_button = $(this).val();
    document.getElementById("order_id").value = fired_button;

});
</script>
<div class="modal fade" id="place_order" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form  action="{% url 'App_Admin:delete_place_order' %}" method="post">{% csrf_token %}
                    <h3 class="text-center text-danger">Delete Order</h3><br>
                    <p class="text-center text-success">Are you sure you want to delete this order?</p>
                    <input name="order_id" id="order_id" value="" type="hidden">
                    <div class="clearfix text-center">
                        <button type="button" data-dismiss="modal" class="cancelbtn btn btn-success">Cancel</button>
                        <button type="submit" class="deletebtn btn btn-danger">Delete</button>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

templates/App_Admin/manage_toprated_placeorder.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-lg-12  m-0 m-auto">
    {%for message in messages %}
        {%if "delete_order" in message.tags %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
</div>
<div class="container">
          <div class="row mb-3">
          <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Top Rated Places Order List</h6>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                    <thead class="thead-light">
                      <tr>
                        <th>No</th>
                        <th>Place Name</th>
                        <th>Order By</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Person</th>
                        <th>Satus</th>
                        <th>Action</th>
                      </tr>

                    </thead>
                    <tbody>
                    {% for g in all_place %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ g.place.title }}</td>
                      <td><a href="{% url 'App_Admin:user_profile' g.user.id %}">{{ g.user.name }}</a></td>
                        <td>{{ g.start_date }}</td>
                        <td>{{ g.end_date }}</td>
                        <td>{{ g.person }}</td>
                        <td>
                            {% if g.ordered == True %}
                            <i class="fa fa-check-circle text-success"></i>
                            {% else %}
                            <i class="fa fa-clock text-danger"></i>
                            {% endif %}
                        </td>
                        <td>
                          <button style="border: none;background: no-repeat;outline: none;" data-toggle="modal" value="{{ g.id }}" data-target="#toprated_place_order">
                                <i class="fa fa-trash text-danger"></i></button>
                            <a href="{% url 'App_Admin:update_toprated_place_order' g.id %}"><i class="text-primary fas fa-fw fa-edit" style="color: #801d3b;"></i></a>
                        </td>
                      </tr>
                     {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
    $("button").click(function() {
    var fired_button = $(this).val();
    document.getElementById("topplace_order_id").value = fired_button;

});
</script>
<div class="modal fade" id="toprated_place_order" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form  action="{% url 'App_Admin:delete_toprated_place_order' %}" method="post">{% csrf_token %}
                    <h3 class="text-center text-danger">Delete Order</h3><br>
                    <p class="text-center text-success">Are you sure you want to delete this order?</p>
                    <input name="topplace_order_id" id="topplace_order_id" value="" type="hidden">
                    <div class="clearfix text-center">
                        <button type="button" data-dismiss="modal" class="cancelbtn btn btn-success">Cancel</button>
                        <button type="submit" class="deletebtn btn btn-danger">Delete</button>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

templates/App_Admin/topratedplace.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-lg-12  m-0 m-auto">
    {%for message in messages %}
        {%if "delete_place" in message.tags %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
</div>
<div class="container">
          <div class="row mb-3">
          <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Top Rated Places</h6>
                  <a class="float-right btn btn-primary" href="{% url 'App_Admin:add_top_rated_place' %}">Add New</a>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                    <thead class="thead-light">
                      <tr>
                        <th>No</th>
                        <th>Place Name</th>
                        <th>Division</th>
                        <th>District</th>
                        <th>Sub District</th>
                        <th>Action</th>
                      </tr>

                    </thead>
                    <tbody>
                    {% for g in all_place %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ g.title }}</td>
                        <td>{{ g.division }}</td>
                        <td>{{ g.district }}</td>
                        <td>{{ g.sub_district }}</td>
                        <td>
                          <button style="border: none;background: no-repeat;outline: none;" data-toggle="modal" value="{{ g.id }}" data-target="#toprated_place">
                                <i class="fa fa-trash text-danger"></i></button>
                            <a href="{% url 'App_Admin:update_toprated_place' g.id %}"><i class="text-primary fas fa-fw fa-edit" style="color: #801d3b;"></i></a>
                        </td>
                      </tr>
                     {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
    $("button").click(function() {
    var fired_button = $(this).val();
    document.getElementById("topratedplace").value = fired_button;

});
</script>
<div class="modal fade" id="toprated_place" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form  action="{% url 'App_Admin:delete_top_rated_place' %}" method="post">{% csrf_token %}
                    <h3 class="text-center text-danger">Delete Top rated Place</h3><br>
                    <p class="text-center text-success">Are you sure you want to delete this Place?</p>
                    <input name="topratedplace" id="topratedplace" value="" type="hidden">
                    <div class="clearfix text-center">
                        <button type="button" data-dismiss="modal" class="cancelbtn btn btn-success">Cancel</button>
                        <button type="submit" class="deletebtn btn btn-danger">Delete</button>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}